// GENERATED by scripts/introspect-boards.mjs — do not edit.
// Column titles/types/status-dropdown-labels straight from Monday (API 2024-10),
// keyed by board slug then column id. Re-run the script to refresh.
import type { BoardSlug } from './boards';
import type { ColMeta } from './dto';

export const COLUMN_META: Record<BoardSlug, Record<string, ColMeta>> = {
  "oportunidades": {
    "name": {
      "id": "name",
      "title": "Name",
      "type": "name"
    },
    "subitems": {
      "id": "subitems",
      "title": "Tasks",
      "type": "subtasks"
    },
    "lookup_mm4g2hqf": {
      "id": "lookup_mm4g2hqf",
      "title": "Utilidad Total",
      "type": "mirror"
    },
    "lookup_mm35sk4e": {
      "id": "lookup_mm35sk4e",
      "title": "Costo Total",
      "type": "mirror"
    },
    "pulse_id_mm0qcq0m": {
      "id": "pulse_id_mm0qcq0m",
      "title": "Folio",
      "type": "item_id"
    },
    "lookup_mm0pt4mj": {
      "id": "lookup_mm0pt4mj",
      "title": "Cantidad Total",
      "type": "mirror"
    },
    "lookup_mm087at6": {
      "id": "lookup_mm087at6",
      "title": "Etapa Costeo",
      "type": "mirror"
    },
    "lookup_mm0cvyfc": {
      "id": "lookup_mm0cvyfc",
      "title": "Utilidad promedio (%)",
      "type": "mirror"
    },
    "lookup_mm00p07m": {
      "id": "lookup_mm00p07m",
      "title": "Total",
      "type": "mirror"
    },
    "lookup_mkznd66k": {
      "id": "lookup_mkznd66k",
      "title": "Subtotal",
      "type": "mirror"
    },
    "lookup_mm1w47fq": {
      "id": "lookup_mm1w47fq",
      "title": "Margen Gob Total",
      "type": "mirror"
    },
    "pulse_log_mkzm4v99": {
      "id": "pulse_log_mkzm4v99",
      "title": "Creación",
      "type": "creation_log"
    },
    "deal_owner": {
      "id": "deal_owner",
      "title": "Vendedor",
      "type": "people"
    },
    "multiple_person_mm0wt53c": {
      "id": "multiple_person_mm0wt53c",
      "title": "Vendedores secundarios",
      "type": "people"
    },
    "multiple_person_mm03qyw9": {
      "id": "multiple_person_mm03qyw9",
      "title": "Compras",
      "type": "people"
    },
    "dropdown_mm03g067": {
      "id": "dropdown_mm03g067",
      "title": "Zona",
      "type": "dropdown",
      "labels": {
        "1": {
          "label": "Noroeste"
        },
        "2": {
          "label": "Norte"
        },
        "3": {
          "label": "Centro"
        },
        "4": {
          "label": "Bajio"
        },
        "5": {
          "label": "Golfo"
        },
        "6": {
          "label": "Sureste"
        },
        "7": {
          "label": "Sur"
        }
      }
    },
    "deal_expected_close_date": {
      "id": "deal_expected_close_date",
      "title": "Fecha Limite",
      "type": "date"
    },
    "button_mkzmq31f": {
      "id": "button_mkzmq31f",
      "title": "Solicitar costeo",
      "type": "button"
    },
    "button_mm4ezref": {
      "id": "button_mm4ezref",
      "title": "En seguimiento",
      "type": "button"
    },
    "button_mm4e6smh": {
      "id": "button_mm4e6smh",
      "title": "En negociación",
      "type": "button"
    },
    "button_mm4eazp1": {
      "id": "button_mm4eazp1",
      "title": "Esperando OC",
      "type": "button"
    },
    "deal_stage": {
      "id": "deal_stage",
      "title": "Etapa",
      "type": "status",
      "labels": {
        "0": {
          "label": "En Seguimiento",
          "color": "#9cd326"
        },
        "1": {
          "label": "Ganada",
          "color": "#037f4c"
        },
        "2": {
          "label": "Perdida",
          "color": "#df2f4a"
        },
        "3": {
          "label": "En Negociacion",
          "color": "#4eccc6"
        },
        "4": {
          "label": "Nueva oportunidad",
          "color": "#9aadbd"
        },
        "5": {
          "label": "Cancelada",
          "color": "#c4c4c4"
        },
        "6": {
          "label": "Cotización",
          "color": "#401694"
        },
        "7": {
          "label": "Costeo en validación",
          "color": "#5559df"
        },
        "8": {
          "label": "Esperando OC",
          "color": "#175a63"
        },
        "9": {
          "label": "Costeo Confirmado",
          "color": "#faa1f1"
        },
        "15": {
          "label": "En costeo",
          "color": "#66ccff"
        }
      }
    },
    "custom_mkrmrgz6": {
      "id": "custom_mkrmrgz6",
      "title": "Actividades",
      "type": "unsupported"
    },
    "deal_contact": {
      "id": "deal_contact",
      "title": "Contacto",
      "type": "board_relation"
    },
    "lookup_mm1bs976": {
      "id": "lookup_mm1bs976",
      "title": "Institución",
      "type": "mirror"
    },
    "lookup_mm0xf2r5": {
      "id": "lookup_mm0xf2r5",
      "title": "Cargo",
      "type": "mirror"
    },
    "button_mkzmwn51": {
      "id": "button_mkzmwn51",
      "title": "Solicitar validacion costeo",
      "type": "button"
    },
    "formula_mkzma2h4": {
      "id": "formula_mkzma2h4",
      "title": "Fecha limite costeo",
      "type": "formula"
    },
    "button_mm0gjpca": {
      "id": "button_mm0gjpca",
      "title": "Regresar a Nueva Oportunidad",
      "type": "button"
    },
    "direct_doc_mkzp55s9": {
      "id": "direct_doc_mkzp55s9",
      "title": "monday Doc v2",
      "type": "direct_doc"
    },
    "date_mm09mv5b": {
      "id": "date_mm09mv5b",
      "title": "Fecha Cotización",
      "type": "date"
    },
    "date_mm09b6nz": {
      "id": "date_mm09b6nz",
      "title": "Fecha solicitud validación costeo",
      "type": "date"
    },
    "date_mm09wqah": {
      "id": "date_mm09wqah",
      "title": "Fecha Creación Proyecto",
      "type": "date"
    },
    "color_mm0ex0ed": {
      "id": "color_mm0ex0ed",
      "title": "Quieres cotizar nuevos productos?",
      "type": "status",
      "labels": {
        "0": {
          "label": "No, productos en catálogo",
          "color": "#ff6d3b"
        },
        "1": {
          "label": "Si, productos nuevos",
          "color": "#225091"
        }
      }
    },
    "file_mm0fgrzq": {
      "id": "file_mm0fgrzq",
      "title": "Cotizaciones generadas",
      "type": "file"
    },
    "file_mm0z6rze": {
      "id": "file_mm0z6rze",
      "title": "Cotizaciones sin precio",
      "type": "file"
    },
    "file_mm0zjras": {
      "id": "file_mm0zjras",
      "title": "Cotizaciones Firmadas",
      "type": "file"
    },
    "button_mm0f4mhx": {
      "id": "button_mm0f4mhx",
      "title": "Generar Cotización",
      "type": "button"
    },
    "date_mm094kzf": {
      "id": "date_mm094kzf",
      "title": "Fecha solicitud costeo",
      "type": "date"
    },
    "button_mm00tzjh": {
      "id": "button_mm00tzjh",
      "title": "Validar Costeo",
      "type": "button"
    },
    "board_relation_mkzsyfmd": {
      "id": "board_relation_mkzsyfmd",
      "title": "Lead",
      "type": "board_relation"
    },
    "button_mm09vr1h": {
      "id": "button_mm09vr1h",
      "title": "Ganar Oportunidad",
      "type": "button"
    },
    "text_mm0gje0": {
      "id": "text_mm0gje0",
      "title": "Vigencia de la cotización",
      "type": "text"
    },
    "long_text_mm1m416j": {
      "id": "long_text_mm1m416j",
      "title": "Comentarios cotización",
      "type": "long_text"
    },
    "text_mm0gjrrd": {
      "id": "text_mm0gjrrd",
      "title": "Tiempo de entrega",
      "type": "text"
    },
    "file_mm0hpefr": {
      "id": "file_mm0hpefr",
      "title": "Inventario Actual (Imagen)",
      "type": "file"
    },
    "board_relation_mm0hw8ew": {
      "id": "board_relation_mm0hw8ew",
      "title": "Proyectos",
      "type": "board_relation"
    },
    "button_mm0pskyc": {
      "id": "button_mm0pskyc",
      "title": "Perder Oportunidad",
      "type": "button"
    },
    "dropdown_mm0mg00": {
      "id": "dropdown_mm0mg00",
      "title": "Razón de Pérdida",
      "type": "dropdown",
      "labels": {
        "1": {
          "label": "Precio"
        },
        "2": {
          "label": "Tiempo de entrega"
        },
        "3": {
          "label": "Competencia"
        },
        "4": {
          "label": "No viable"
        },
        "5": {
          "label": "Falta info por parte del vendedor"
        }
      }
    },
    "text_mm47xmh": {
      "id": "text_mm47xmh",
      "title": "Comentario de Pérdida",
      "type": "text"
    },
    "date_mm0mc3dj": {
      "id": "date_mm0mc3dj",
      "title": "Fecha Validación Costeo",
      "type": "date"
    },
    "file_mm10k65a": {
      "id": "file_mm10k65a",
      "title": "Solicitud Costeo",
      "type": "file"
    },
    "pulse_updated_mm16td5m": {
      "id": "pulse_updated_mm16td5m",
      "title": "Última actualización",
      "type": "last_updated"
    },
    "multiple_person_mm1m73qp": {
      "id": "multiple_person_mm1m73qp",
      "title": "Responsable compras",
      "type": "people"
    },
    "pulse_updated_mm342p9c": {
      "id": "pulse_updated_mm342p9c",
      "title": "Última actualización 1",
      "type": "last_updated"
    },
    "text_mm3q450n": {
      "id": "text_mm3q450n",
      "title": "Event ID",
      "type": "text"
    },
    "boolean_mm3qf8yv": {
      "id": "boolean_mm3qf8yv",
      "title": "Sector Publico",
      "type": "checkbox"
    },
    "boolean_mm3q9zxm": {
      "id": "boolean_mm3q9zxm",
      "title": "Origen Web",
      "type": "checkbox"
    },
    "link_mm468m26": {
      "id": "link_mm468m26",
      "title": "Carpeta Drive",
      "type": "link"
    },
    "color_mm47f0ca": {
      "id": "color_mm47f0ca",
      "title": "Tipo de cotización",
      "type": "status",
      "labels": {
        "0": {
          "label": "Licitación",
          "color": "#007eb5"
        },
        "1": {
          "label": "Estudio de mercado",
          "color": "#ff7575"
        },
        "2": {
          "label": "Venta Directa",
          "color": "#ff5ac4"
        }
      }
    }
  },
  "oportunidades_sub": {
    "name": {
      "id": "name",
      "title": "Name",
      "type": "name"
    },
    "board_relation_mkzmafgp": {
      "id": "board_relation_mkzmafgp",
      "title": "Producto (auto)",
      "type": "board_relation"
    },
    "color_mm1eq4a0": {
      "id": "color_mm1eq4a0",
      "title": "Recosteo?",
      "type": "status",
      "labels": {
        "1": {
          "label": "Si",
          "color": "#225091"
        },
        "5": {
          "label": "No",
          "color": "#c4c4c4"
        }
      }
    },
    "color_mm084gvf": {
      "id": "color_mm084gvf",
      "title": "Etapa Costeo",
      "type": "status",
      "labels": {
        "0": {
          "label": "En curso",
          "color": "#fdab3d"
        },
        "1": {
          "label": "Listo",
          "color": "#00c875"
        },
        "2": {
          "label": "Detenido",
          "color": "#df2f4a"
        },
        "3": {
          "label": "Modificado",
          "color": "#007eb5"
        },
        "5": {
          "label": "No iniciado",
          "color": "#c4c4c4"
        }
      }
    },
    "text_mm0bxy39": {
      "id": "text_mm0bxy39",
      "title": "SKU",
      "type": "text"
    },
    "lookup_mm07x7e7": {
      "id": "lookup_mm07x7e7",
      "title": "Tipo de Producto",
      "type": "mirror"
    },
    "lookup_mkzn7x9a": {
      "id": "lookup_mkzn7x9a",
      "title": "SKU (auto)",
      "type": "mirror"
    },
    "lookup_mm0xn98d": {
      "id": "lookup_mm0xn98d",
      "title": "Marca",
      "type": "mirror"
    },
    "lookup_mkznm0h3": {
      "id": "lookup_mkznm0h3",
      "title": "Colores disponibles",
      "type": "mirror"
    },
    "lookup_mm1cs054": {
      "id": "lookup_mm1cs054",
      "title": "Proveedor ID",
      "type": "mirror"
    },
    "lookup_mm1ck0mr": {
      "id": "lookup_mm1ck0mr",
      "title": "Nombre Proveedor (conectada)",
      "type": "mirror"
    },
    "lookup_mm1dxqrg": {
      "id": "lookup_mm1dxqrg",
      "title": "Razon Social Proveedor",
      "type": "mirror"
    },
    "lookup_mm0w4f4v": {
      "id": "lookup_mm0w4f4v",
      "title": "Unidad",
      "type": "mirror"
    },
    "lookup_mm0x4kda": {
      "id": "lookup_mm0x4kda",
      "title": "Nombre del Producto",
      "type": "mirror"
    },
    "lookup_mm0xw8p7": {
      "id": "lookup_mm0xw8p7",
      "title": "Descripción Cotización",
      "type": "mirror"
    },
    "lookup_mm19c0b6": {
      "id": "lookup_mm19c0b6",
      "title": "Tallas",
      "type": "mirror"
    },
    "text_mm07s2mg": {
      "id": "text_mm07s2mg",
      "title": "Color",
      "type": "text"
    },
    "formula_mm093z5b": {
      "id": "formula_mm093z5b",
      "title": "Color ok?",
      "type": "formula"
    },
    "text_mm0bkm1j": {
      "id": "text_mm0bkm1j",
      "title": "Producto",
      "type": "text"
    },
    "numeric_mkzm6399": {
      "id": "numeric_mkzm6399",
      "title": "Cantidad",
      "type": "numbers"
    },
    "formula_mm1b1g1p": {
      "id": "formula_mm1b1g1p",
      "title": "Descripción ok?",
      "type": "formula"
    },
    "formula_mm0adstd": {
      "id": "formula_mm0adstd",
      "title": "Cantidad ok?",
      "type": "formula"
    },
    "color_mm1b34bg": {
      "id": "color_mm1b34bg",
      "title": "Embellecimiento",
      "type": "status",
      "labels": {
        "1": {
          "label": "Con Embellecimiento",
          "color": "#225091"
        },
        "5": {
          "label": "Sin Embellecimiento",
          "color": "#c4c4c4"
        }
      }
    },
    "long_text_mm1bj4pt": {
      "id": "long_text_mm1bj4pt",
      "title": "Descripción Embellecimientos",
      "type": "long_text"
    },
    "long_text_mm1hyszv": {
      "id": "long_text_mm1hyszv",
      "title": "Comentarios Ventas",
      "type": "long_text"
    },
    "long_text_mm1b9bh8": {
      "id": "long_text_mm1b9bh8",
      "title": "Costo Embellecimiento",
      "type": "long_text"
    },
    "lookup_mm11t8gj": {
      "id": "lookup_mm11t8gj",
      "title": "Moneda",
      "type": "mirror"
    },
    "numeric_mm0bph99": {
      "id": "numeric_mm0bph99",
      "title": "Costo Distr. C/U",
      "type": "numbers"
    },
    "lookup_mm0bdwb5": {
      "id": "lookup_mm0bdwb5",
      "title": "Descuento (auto)",
      "type": "mirror"
    },
    "numeric_mkzn2q51": {
      "id": "numeric_mkzn2q51",
      "title": "Descuento Distr. %",
      "type": "numbers"
    },
    "formula_mkznqx51": {
      "id": "formula_mkznqx51",
      "title": "Descuento",
      "type": "formula"
    },
    "formula_mkzngnjm": {
      "id": "formula_mkzngnjm",
      "title": "Costo Real C/U",
      "type": "formula"
    },
    "numeric_mm0rvhgs": {
      "id": "numeric_mm0rvhgs",
      "title": "Valor de Conversión",
      "type": "numbers"
    },
    "formula_mm0rqjv1": {
      "id": "formula_mm0rqjv1",
      "title": "Costo Convertido",
      "type": "formula"
    },
    "lookup_mm0bbz02": {
      "id": "lookup_mm0bbz02",
      "title": "Gastos % (auto)",
      "type": "mirror"
    },
    "numeric_mkzngs9x": {
      "id": "numeric_mkzngs9x",
      "title": "Gastos %",
      "type": "numbers"
    },
    "numeric_mm0gxvpa": {
      "id": "numeric_mm0gxvpa",
      "title": "Costo Total Embellecimento C/U",
      "type": "numbers"
    },
    "formula_mkznpfgg": {
      "id": "formula_mkznpfgg",
      "title": "Costo Total Unitario",
      "type": "formula"
    },
    "formula_mkznrm5a": {
      "id": "formula_mkznrm5a",
      "title": "Costo Total",
      "type": "formula"
    },
    "numeric_mkznpn83": {
      "id": "numeric_mkznpn83",
      "title": "Techo",
      "type": "numbers"
    },
    "numeric_mm2qzzbe": {
      "id": "numeric_mm2qzzbe",
      "title": "Precio de Venta (formula)",
      "type": "numbers"
    },
    "numeric_mkzneg3d": {
      "id": "numeric_mkzneg3d",
      "title": "Precio de Venta C/U",
      "type": "numbers"
    },
    "numeric_mm0cg0bm": {
      "id": "numeric_mm0cg0bm",
      "title": "IVA",
      "type": "numbers"
    },
    "formula_mkznmjh6": {
      "id": "formula_mkznmjh6",
      "title": "Subtotal",
      "type": "formula"
    },
    "formula_mm0rtdqp": {
      "id": "formula_mm0rtdqp",
      "title": "IVA",
      "type": "formula"
    },
    "formula_mm00xy0n": {
      "id": "formula_mm00xy0n",
      "title": "Total Con IVA",
      "type": "formula"
    },
    "numeric_mkznnm5s": {
      "id": "numeric_mkznnm5s",
      "title": "Margen Gob (MG)  %",
      "type": "numbers"
    },
    "formula_mkznsb7m": {
      "id": "formula_mkznsb7m",
      "title": "Margen Gob Total",
      "type": "formula"
    },
    "formula_mkznpp33": {
      "id": "formula_mkznpp33",
      "title": "Margen Gob",
      "type": "formula"
    },
    "formula_mkzn28xk": {
      "id": "formula_mkzn28xk",
      "title": "Diferencia",
      "type": "formula"
    },
    "formula_mkzne7gd": {
      "id": "formula_mkzne7gd",
      "title": "Utilidad",
      "type": "formula"
    },
    "formula_mkznry25": {
      "id": "formula_mkznry25",
      "title": "Utilidad Total",
      "type": "formula"
    },
    "formula_mkznpw5p": {
      "id": "formula_mkznpw5p",
      "title": "Utilidad (%)",
      "type": "formula"
    },
    "pulse_log_mm0yj8rw": {
      "id": "pulse_log_mm0yj8rw",
      "title": "Creación Producto",
      "type": "creation_log"
    },
    "lookup_mm0z4exs": {
      "id": "lookup_mm0z4exs",
      "title": "airtable_id",
      "type": "mirror"
    },
    "color_mm1r1052": {
      "id": "color_mm1r1052",
      "title": "Nuevo producto",
      "type": "status",
      "labels": {
        "1": {
          "label": "Si",
          "color": "#00c875"
        },
        "5": {
          "label": "No",
          "color": "#c4c4c4"
        }
      }
    },
    "lookup_mm1tjv9n": {
      "id": "lookup_mm1tjv9n",
      "title": "Historial de Precios",
      "type": "mirror"
    },
    "file_mm5akjy5": {
      "id": "file_mm5akjy5",
      "title": "Imagen embellecimiento",
      "type": "file"
    }
  },
  "proyectos": {
    "name": {
      "id": "name",
      "title": "Name",
      "type": "name"
    },
    "subitems": {
      "id": "subitems",
      "title": "Subitems",
      "type": "subtasks"
    },
    "lookup_mm20g4n6": {
      "id": "lookup_mm20g4n6",
      "title": "Estado de productos",
      "type": "mirror"
    },
    "pulse_id_mm1a12gy": {
      "id": "pulse_id_mm1a12gy",
      "title": "Folio",
      "type": "item_id"
    },
    "project_status": {
      "id": "project_status",
      "title": "Estado Proyecto",
      "type": "status",
      "labels": {
        "0": {
          "label": "En confirmacion de tallas",
          "color": "#66ccff"
        },
        "1": {
          "label": "Proyecto Terminado",
          "color": "#037f4c"
        },
        "2": {
          "label": "Ordenes de compra listas",
          "color": "#007eb5"
        },
        "3": {
          "label": "Ejecución",
          "color": "#9d50dd"
        },
        "4": {
          "label": "Tallas Confirmadas",
          "color": "#fdab3d"
        },
        "5": {
          "label": "Desglose de tallas",
          "color": "#c4c4c4"
        }
      }
    },
    "lookup_mm0mbkjk": {
      "id": "lookup_mm0mbkjk",
      "title": "Cantidad Tallas",
      "type": "mirror"
    },
    "pulse_log_mm0hdr21": {
      "id": "pulse_log_mm0hdr21",
      "title": "Creación",
      "type": "creation_log"
    },
    "pulse_updated_mm0mjstj": {
      "id": "pulse_updated_mm0mjstj",
      "title": "Última actualización",
      "type": "last_updated"
    },
    "date_mm0m1vfv": {
      "id": "date_mm0m1vfv",
      "title": "Fecha Entrega",
      "type": "date"
    },
    "color_mm0md4z8": {
      "id": "color_mm0md4z8",
      "title": "Estado Facturación",
      "type": "status",
      "labels": {
        "0": {
          "label": "Solicitada",
          "color": "#fdab3d"
        },
        "1": {
          "label": "Facturada",
          "color": "#00c875"
        },
        "2": {
          "label": "Cancelada",
          "color": "#df2f4a"
        },
        "5": {
          "label": "Pendiente",
          "color": "#c4c4c4"
        }
      }
    },
    "color_mm0mcrjq": {
      "id": "color_mm0mcrjq",
      "title": "Estado Pago",
      "type": "status",
      "labels": {
        "0": {
          "label": "Problemas de pago",
          "color": "#fdab3d"
        },
        "1": {
          "label": "Pagado",
          "color": "#00c875"
        },
        "2": {
          "label": "Vencido",
          "color": "#df2f4a"
        },
        "5": {
          "label": "Por Cobrar",
          "color": "#c4c4c4"
        }
      }
    },
    "date_mm0mwqzw": {
      "id": "date_mm0mwqzw",
      "title": "Fecha de Pago Real",
      "type": "date"
    },
    "multiple_person_mm0hrnqq": {
      "id": "multiple_person_mm0hrnqq",
      "title": "Vendedor",
      "type": "people"
    },
    "project_owner": {
      "id": "project_owner",
      "title": "Compras",
      "type": "people"
    },
    "board_relation_mm0hb0gy": {
      "id": "board_relation_mm0hb0gy",
      "title": "Contacto",
      "type": "board_relation"
    },
    "lookup_mm1dwn6": {
      "id": "lookup_mm1dwn6",
      "title": "Institucion",
      "type": "mirror"
    },
    "lookup_mm1d1546": {
      "id": "lookup_mm1d1546",
      "title": "Cargo",
      "type": "mirror"
    },
    "dropdown_mm0hnyv": {
      "id": "dropdown_mm0hnyv",
      "title": "Zona",
      "type": "dropdown",
      "labels": {
        "0": {
          "label": "Sureste"
        },
        "1": {
          "label": "Bajio"
        },
        "2": {
          "label": "Norte"
        },
        "3": {
          "label": "Sur"
        },
        "4": {
          "label": "Centro"
        },
        "5": {
          "label": "Noroeste"
        },
        "6": {
          "label": "Golfo"
        }
      }
    },
    "file_mm0hwapr": {
      "id": "file_mm0hwapr",
      "title": "Cotizaciones",
      "type": "file"
    },
    "file_mm0hcrtz": {
      "id": "file_mm0hcrtz",
      "title": "OC interna",
      "type": "file"
    },
    "file_mm1dm11c": {
      "id": "file_mm1dm11c",
      "title": "OC Int. Firmada",
      "type": "file"
    },
    "date_mm21c5ka": {
      "id": "date_mm21c5ka",
      "title": "Fecha OC Int. Firmada",
      "type": "date"
    },
    "multiple_person_mm164em1": {
      "id": "multiple_person_mm164em1",
      "title": "Elaborado por",
      "type": "people"
    },
    "multiple_person_mm16qysk": {
      "id": "multiple_person_mm16qysk",
      "title": "Revisado por",
      "type": "people"
    },
    "multiple_person_mm169k2f": {
      "id": "multiple_person_mm169k2f",
      "title": "Autorizado por",
      "type": "people"
    },
    "file_mm0hj9pn": {
      "id": "file_mm0hj9pn",
      "title": "OC Proveedores",
      "type": "file"
    },
    "file_mm1g7cqz": {
      "id": "file_mm1g7cqz",
      "title": "OC Prov. Firmada",
      "type": "file"
    },
    "file_mm0hayh4": {
      "id": "file_mm0hayh4",
      "title": "Cotización Firmada Institucion",
      "type": "file"
    },
    "board_relation_mm0hf0y3": {
      "id": "board_relation_mm0hf0y3",
      "title": "Oportunidad",
      "type": "board_relation"
    },
    "button_mm0prtfk": {
      "id": "button_mm0prtfk",
      "title": "Generar OC Proveedor",
      "type": "button"
    },
    "button_mm0p4f6f": {
      "id": "button_mm0p4f6f",
      "title": "COMPRAS : Validar tallas",
      "type": "button"
    },
    "lookup_mm0pd55m": {
      "id": "lookup_mm0pd55m",
      "title": "Cantidad Oportunidad",
      "type": "mirror"
    },
    "link_mm1amwz8": {
      "id": "link_mm1amwz8",
      "title": "Link Tallas",
      "type": "link"
    },
    "button_mm1a7qtd": {
      "id": "button_mm1a7qtd",
      "title": "VENDEDOR: validar tallas",
      "type": "button"
    },
    "lookup_mm1d56mp": {
      "id": "lookup_mm1d56mp",
      "title": "Folio Oportunidad",
      "type": "mirror"
    },
    "button_mm21f5n2": {
      "id": "button_mm21f5n2",
      "title": "Pasar Proyecto a Ejecución",
      "type": "button"
    },
    "file_mm3393nf": {
      "id": "file_mm3393nf",
      "title": "Subir documentacion  (OC/cotizacion firmada)",
      "type": "file"
    },
    "file_mm478mkq": {
      "id": "file_mm478mkq",
      "title": "Imagen/Referencia de embellecimientos",
      "type": "file"
    },
    "file_mm33yv4p": {
      "id": "file_mm33yv4p",
      "title": "OC/contrato/cotización firmada (oculto)",
      "type": "file"
    },
    "link_mm462saa": {
      "id": "link_mm462saa",
      "title": "Carpeta Drive",
      "type": "link"
    },
    "button_mm46pc4a": {
      "id": "button_mm46pc4a",
      "title": "Regenerar Tallas",
      "type": "button"
    },
    "text_mm4cct6a": {
      "id": "text_mm4cct6a",
      "title": "Método de pago",
      "type": "text"
    },
    "text_mm4cdyjb": {
      "id": "text_mm4cdyjb",
      "title": "Condiciones de pago",
      "type": "text"
    },
    "text_mm4c74f8": {
      "id": "text_mm4c74f8",
      "title": "Comentarios",
      "type": "text"
    },
    "pulse_updated_mm4dz2mj": {
      "id": "pulse_updated_mm4dz2mj",
      "title": "Última actualización 1",
      "type": "last_updated"
    },
    "file_mm4pa2h8": {
      "id": "file_mm4pa2h8",
      "title": "Acta de Entrega",
      "type": "file"
    },
    "color_mm52csps": {
      "id": "color_mm52csps",
      "title": "Documentacion",
      "type": "status",
      "labels": {
        "1": {
          "label": "Documentacion Cargada",
          "color": "#00c875"
        },
        "2": {
          "label": "Documentacion Faltante",
          "color": "#df2f4a"
        },
        "5": {
          "label": "Proyecto Nuevo",
          "color": "#c4c4c4"
        }
      }
    },
    "date_mm525k42": {
      "id": "date_mm525k42",
      "title": "Fecha de Creacion",
      "type": "date"
    }
  },
  "proyectos_sub": {
    "name": {
      "id": "name",
      "title": "Name",
      "type": "name"
    },
    "text_mm0hs17x": {
      "id": "text_mm0hs17x",
      "title": "Producto",
      "type": "text"
    },
    "board_relation_mm1cfgv5": {
      "id": "board_relation_mm1cfgv5",
      "title": "Proveedor",
      "type": "board_relation"
    },
    "text_mm0h4a1c": {
      "id": "text_mm0h4a1c",
      "title": "Color",
      "type": "text"
    },
    "numeric_mm0hj2q4": {
      "id": "numeric_mm0hj2q4",
      "title": "Cantidad",
      "type": "numbers"
    },
    "text_mm1antcb": {
      "id": "text_mm1antcb",
      "title": "Talla",
      "type": "text"
    },
    "color_mm0hqf79": {
      "id": "color_mm0hqf79",
      "title": "Estado del producto",
      "type": "status",
      "labels": {
        "0": {
          "label": "Con vendedor para entrega cliente",
          "color": "#9d50dd"
        },
        "1": {
          "label": "En CMP para embellecer",
          "color": "#74afcc"
        },
        "2": {
          "label": "En embellecimiento",
          "color": "#5559df"
        },
        "3": {
          "label": "En CMP para entrega cliente",
          "color": "#784bd1"
        },
        "4": {
          "label": "En produccion",
          "color": "#a1e3f6"
        },
        "5": {
          "label": "OC Proveedor lista",
          "color": "#c4c4c4"
        },
        "6": {
          "label": "Entregado",
          "color": "#037f4c"
        },
        "7": {
          "label": "Incidencia/Retraso",
          "color": "#df2f4a"
        },
        "8": {
          "label": "OC Proveedor enviada",
          "color": "#a9bee8"
        },
        "9": {
          "label": "Pendiente OC al Prov",
          "color": "#e484bd"
        }
      }
    },
    "text_mm20gzsb": {
      "id": "text_mm20gzsb",
      "title": "Comentario de Estado",
      "type": "text"
    },
    "date_mm20xdtm": {
      "id": "date_mm20xdtm",
      "title": "Fecha estimada de entrega proveedor",
      "type": "date"
    },
    "date_mm20fq6t": {
      "id": "date_mm20fq6t",
      "title": "Fecha OC Proveedor enviada (auto)",
      "type": "date"
    },
    "text_mm52x1bx": {
      "id": "text_mm52x1bx",
      "title": "Producción o Aplicacion)",
      "type": "text"
    },
    "date_mm20y5t3": {
      "id": "date_mm20y5t3",
      "title": "Fecha en CMP para embellecer",
      "type": "date"
    },
    "date_mm21p1ex": {
      "id": "date_mm21p1ex",
      "title": "Fecha en Embellecimiento",
      "type": "date"
    },
    "text_mm0hyrfs": {
      "id": "text_mm0hyrfs",
      "title": "SKU",
      "type": "text"
    },
    "date_mm217ms0": {
      "id": "date_mm217ms0",
      "title": "Fecha en CMP Para entrega cliente",
      "type": "date"
    },
    "date_mm21w46m": {
      "id": "date_mm21w46m",
      "title": "Fecha Con vendedor Para entrega cliente",
      "type": "date"
    },
    "date_mm20t4kr": {
      "id": "date_mm20t4kr",
      "title": "Fecha real entrega a cliente",
      "type": "date"
    },
    "text_mm1a5yyq": {
      "id": "text_mm1a5yyq",
      "title": "Género",
      "type": "text"
    },
    "numeric_mm1dj4fp": {
      "id": "numeric_mm1dj4fp",
      "title": "Costo Distr. C/U",
      "type": "numbers"
    },
    "text_mm0mzet0": {
      "id": "text_mm0mzet0",
      "title": "Número de Guía",
      "type": "text"
    },
    "text_mm1gdsvg": {
      "id": "text_mm1gdsvg",
      "title": "Moneda",
      "type": "text"
    },
    "numeric_mm1dmsaz": {
      "id": "numeric_mm1dmsaz",
      "title": "Descuento",
      "type": "numbers"
    },
    "lookup_mm1d2y9b": {
      "id": "lookup_mm1d2y9b",
      "title": "Razon Social",
      "type": "mirror"
    },
    "long_text_mm1cqh8e": {
      "id": "long_text_mm1cqh8e",
      "title": "Espalda",
      "type": "long_text"
    },
    "long_text_mm1cyqts": {
      "id": "long_text_mm1cyqts",
      "title": "Frente derecho",
      "type": "long_text"
    },
    "long_text_mm1c59cg": {
      "id": "long_text_mm1c59cg",
      "title": "Frente izquierdo",
      "type": "long_text"
    },
    "long_text_mm1c2eyf": {
      "id": "long_text_mm1c2eyf",
      "title": "Manga derecha/costado derecho",
      "type": "long_text"
    },
    "long_text_mm1cyq91": {
      "id": "long_text_mm1cyq91",
      "title": "Manga izquierda/costado izquierdo",
      "type": "long_text"
    },
    "long_text_mm1c6ya0": {
      "id": "long_text_mm1c6ya0",
      "title": "Etiqueta del fabricante",
      "type": "long_text"
    },
    "long_text_mm1cnbbr": {
      "id": "long_text_mm1cnbbr",
      "title": "Etiqueta de propiedad",
      "type": "long_text"
    },
    "long_text_mm2077h1": {
      "id": "long_text_mm2077h1",
      "title": "Otros",
      "type": "long_text"
    },
    "lookup_mm2145g": {
      "id": "lookup_mm2145g",
      "title": "Correo Proveedor",
      "type": "mirror"
    },
    "date_mm21swc5": {
      "id": "date_mm21swc5",
      "title": "Fecha prometida proveedor",
      "type": "date"
    },
    "file_mm4pfh5q": {
      "id": "file_mm4pfh5q",
      "title": "Pesos y dimensiones",
      "type": "file"
    },
    "multiple_person_mm4pc2ns": {
      "id": "multiple_person_mm4pc2ns",
      "title": "Encargado Logistica",
      "type": "people"
    },
    "text_mm4ph3a9": {
      "id": "text_mm4ph3a9",
      "title": "Instrucción Logistica",
      "type": "text"
    },
    "text_mm4pywyx": {
      "id": "text_mm4pywyx",
      "title": "Folio/Guia de recolección",
      "type": "text"
    },
    "file_mm4pz90b": {
      "id": "file_mm4pz90b",
      "title": "Foto de Guia/Folio",
      "type": "file"
    },
    "file_mm4pc4tj": {
      "id": "file_mm4pc4tj",
      "title": "Evidencia recolección",
      "type": "file"
    },
    "boolean_mm4p7eqb": {
      "id": "boolean_mm4p7eqb",
      "title": "Confirmar tallas completas",
      "type": "checkbox"
    },
    "date_mm4p59q2": {
      "id": "date_mm4p59q2",
      "title": "Fecha confirmacion",
      "type": "date"
    },
    "text_mm56dbkm": {
      "id": "text_mm56dbkm",
      "title": "Unidad",
      "type": "text"
    }
  },
  "productos": {
    "name": {
      "id": "name",
      "title": "Name",
      "type": "name"
    },
    "subtasks_mkzm11w4": {
      "id": "subtasks_mkzm11w4",
      "title": "Subitems",
      "type": "subtasks"
    },
    "product_and_service_sku": {
      "id": "product_and_service_sku",
      "title": "SKU",
      "type": "text"
    },
    "product_and_service_description": {
      "id": "product_and_service_description",
      "title": "Marca",
      "type": "long_text"
    },
    "board_relation_mm1cwqky": {
      "id": "board_relation_mm1cwqky",
      "title": "Proveedor",
      "type": "board_relation"
    },
    "lookup_mm1cyy7f": {
      "id": "lookup_mm1cyy7f",
      "title": "Proveedor ID",
      "type": "mirror"
    },
    "lookup_mm1dv3jy": {
      "id": "lookup_mm1dv3jy",
      "title": "Razon Social Proveedor",
      "type": "mirror"
    },
    "direct_doc_mkzm87ge": {
      "id": "direct_doc_mkzm87ge",
      "title": "monday Doc v2",
      "type": "direct_doc"
    },
    "dropdown_mkztty4b": {
      "id": "dropdown_mkztty4b",
      "title": "Color",
      "type": "dropdown",
      "labels": {
        "3": {
          "label": "Negro"
        },
        "4": {
          "label": "Caqui"
        },
        "5": {
          "label": "Midnight Navy"
        },
        "6": {
          "label": "Cafe"
        },
        "7": {
          "label": "Black"
        },
        "8": {
          "label": "Kangaroo"
        },
        "9": {
          "label": "Ranger Green"
        },
        "10": {
          "label": "BLACK"
        },
        "11": {
          "label": "KHAKI"
        },
        "12": {
          "label": "KANGAROO"
        },
        "13": {
          "label": "RANGER GREEN"
        },
        "14": {
          "label": "DARK NAVY"
        },
        "15": {
          "label": "FRENCH BLUE"
        },
        "16": {
          "label": "MIDNIGHT NVY"
        },
        "17": {
          "label": "UNIFORM WHTE"
        },
        "18": {
          "label": "BROWN"
        },
        "19": {
          "label": "SHERIFF GRN"
        },
        "20": {
          "label": "STORM"
        },
        "21": {
          "label": "TDU KHAKI"
        },
        "22": {
          "label": "TDU GREEN"
        },
        "23": {
          "label": "WHITE"
        },
        "24": {
          "label": "CHARCOAL"
        },
        "25": {
          "label": "COYOTE"
        },
        "26": {
          "label": "TUNDRA"
        },
        "27": {
          "label": "MULTICAM"
        },
        "28": {
          "label": "DOUBLE TAP"
        },
        "29": {
          "label": "STONE"
        },
        "30": {
          "label": "BATTLE BROWN"
        },
        "31": {
          "label": "BURNT"
        },
        "32": {
          "label": "FLAT DK ERTH"
        },
        "33": {
          "label": "RANGE RED"
        },
        "34": {
          "label": "CASHMERE"
        },
        "35": {
          "label": "FLINT"
        },
        "36": {
          "label": "US DK COYOTE"
        },
        "37": {
          "label": "HIGH VIS YLW"
        },
        "38": {
          "label": "ROYAL BLUE"
        },
        "39": {
          "label": "SPRUCE GREEN"
        },
        "40": {
          "label": "SANDSTONE"
        },
        "41": {
          "label": "VOLCANIC"
        },
        "42": {
          "label": "DARK COYOTE"
        },
        "43": {
          "label": "HEATHER GREY"
        },
        "44": {
          "label": "SILVER TAN"
        },
        "45": {
          "label": "ACADEMY BLUE"
        },
        "46": {
          "label": "FIRE MED BLU"
        },
        "47": {
          "label": "L.E. GREEN"
        },
        "48": {
          "label": "DESERT TAN"
        },
        "49": {
          "label": "UNIFORM WHITE"
        },
        "50": {
          "label": "MULTI"
        },
        "51": {
          "label": "AZUL MARINO"
        },
        "52": {
          "label": "LE GREEN"
        },
        "53": {
          "label": "SAND DUNE"
        },
        "54": {
          "label": "MAJOR BROWN"
        },
        "55": {
          "label": "SHERIFF TAN"
        },
        "56": {
          "label": "FIRE NAVY"
        },
        "57": {
          "label": "CAVIAR"
        },
        "58": {
          "label": "NEGRO"
        },
        "59": {
          "label": "GRAY"
        },
        "60": {
          "label": "LIGHT BLUE"
        },
        "61": {
          "label": "GRIS"
        },
        "62": {
          "label": "VERDE OD"
        },
        "63": {
          "label": "ARENA"
        },
        "64": {
          "label": "BLANCO"
        },
        "65": {
          "label": "CAFE KODIAK"
        },
        "66": {
          "label": "KRYPTEK"
        },
        "67": {
          "label": "PENCOTT"
        },
        "68": {
          "label": "A-TACS"
        },
        "69": {
          "label": "AMARILLO"
        },
        "70": {
          "label": "LICENCIA"
        },
        "71": {
          "label": "CREDITOS"
        },
        "72": {
          "label": "LASSER ROJO"
        },
        "73": {
          "label": "LASSER VERDE"
        },
        "74": {
          "label": "ROJO"
        },
        "75": {
          "label": "ROSA"
        },
        "76": {
          "label": "AMARILLO LIMÓN"
        },
        "77": {
          "label": "AZUL"
        },
        "78": {
          "label": "NARANJA"
        },
        "79": {
          "label": "VERDE"
        },
        "80": {
          "label": "ORO"
        },
        "81": {
          "label": "BROWN GREY"
        },
        "82": {
          "label": "STEEL GREY"
        },
        "83": {
          "label": "NAVY BLUE"
        },
        "84": {
          "label": "MULTICAM BLACK"
        },
        "85": {
          "label": "DENIM"
        },
        "86": {
          "label": "FLECKTRAN"
        },
        "87": {
          "label": "TAN"
        },
        "88": {
          "label": "A-TACS U|CON"
        },
        "89": {
          "label": "CCE"
        },
        "90": {
          "label": "VEGETATO"
        },
        "91": {
          "label": "CHIVE GREEN"
        },
        "92": {
          "label": "DESERT GREY"
        },
        "93": {
          "label": "MULTICAM ALPINE"
        },
        "94": {
          "label": "MULTICAM ARID"
        },
        "95": {
          "label": "VARIOS"
        },
        "96": {
          "label": "DORADO"
        },
        "97": {
          "label": "N/a"
        },
        "98": {
          "label": "BEIGE"
        },
        "99": {
          "label": "NEGRO CON ROJO"
        },
        "100": {
          "label": "AZUL MARINO CON ROJO"
        },
        "101": {
          "label": "GRIS OXFORD"
        },
        "102": {
          "label": "AZUL MARINO CON AMARILLO"
        },
        "103": {
          "label": "MOZTAZA"
        },
        "104": {
          "label": "AMARILLO NEON"
        },
        "105": {
          "label": "NARANJA NEON"
        },
        "106": {
          "label": "AMARILLO NEON Y AZUL MEDIA NOCHE"
        },
        "107": {
          "label": "VERDE NEON Y AZUL MEDIA NOCHE"
        },
        "108": {
          "label": "AZUL CLARO"
        },
        "109": {
          "label": "AZUL OXFORD"
        },
        "110": {
          "label": "MIL RAYAS AZUL"
        },
        "111": {
          "label": "Niquel"
        },
        "112": {
          "label": "AZUL MARINO OSCURO"
        },
        "113": {
          "label": "VERDE OLIVA"
        },
        "114": {
          "label": "VERD OD"
        },
        "115": {
          "label": "VERDE BANDERA"
        },
        "116": {
          "label": "VERDE MILITAR"
        },
        "117": {
          "label": "AZUL REY"
        },
        "118": {
          "label": "VERDE FLUORESCENTE"
        },
        "119": {
          "label": "NARANJA FLUORESCENTE"
        },
        "120": {
          "label": "AZUL MEZCLILLA"
        },
        "121": {
          "label": "Azul Celeste/Blanco"
        },
        "122": {
          "label": "Azul Marino combinacion Gris"
        },
        "123": {
          "label": "VERDE LIMON"
        },
        "124": {
          "label": "AMARILLO MANGO"
        },
        "125": {
          "label": "KAKI"
        },
        "126": {
          "label": "GUINDA"
        },
        "127": {
          "label": "MULTICAM ORIGINAL"
        },
        "128": {
          "label": "MULTICAM TROPIC"
        },
        "129": {
          "label": "NEGRO CON NARANJA"
        },
        "130": {
          "label": "AZUL MARINO CON NARANJA"
        },
        "131": {
          "label": "PIXEL URBANO"
        },
        "132": {
          "label": "PIXEL DESIERTO"
        },
        "133": {
          "label": "PIXEL MARSHALL"
        },
        "134": {
          "label": "VINO"
        },
        "135": {
          "label": "KRYPTEK TYPHON"
        },
        "136": {
          "label": "KRYPTEK HIGHLANDER"
        },
        "137": {
          "label": "KRYPTEK MANDRAKE"
        },
        "138": {
          "label": "N/A"
        },
        "139": {
          "label": "FIRE RED"
        },
        "140": {
          "label": "MUSHROOM"
        },
        "141": {
          "label": "FATIGUE"
        },
        "142": {
          "label": "ARCTIC"
        },
        "143": {
          "label": "COBALT BLUE"
        },
        "144": {
          "label": "GANGER GREEN 2"
        },
        "145": {
          "label": "STORM 2"
        },
        "146": {
          "label": "DIPLOMAT"
        },
        "147": {
          "label": "TANK GREEN"
        },
        "148": {
          "label": "Arena del desierto"
        },
        "149": {
          "label": "FLUORSCN ORG"
        },
        "150": {
          "label": "FIG"
        },
        "151": {
          "label": "SAGE GREEN"
        },
        "152": {
          "label": "WOODLAND CAMO"
        },
        "153": {
          "label": "CHOCOLATE"
        },
        "154": {
          "label": "ACU TAN"
        },
        "155": {
          "label": "NEGRO CON AMARILLO"
        },
        "156": {
          "label": "PLATA"
        },
        "157": {
          "label": "MED BLUE"
        },
        "158": {
          "label": "FIRE MED BLUE"
        },
        "159": {
          "label": "BLANCO CON GRIS"
        },
        "160": {
          "label": "UMBER BROWN"
        },
        "161": {
          "label": "ANCIENT FOSSIL"
        },
        "162": {
          "label": "MEDIUM GREY"
        },
        "163": {
          "label": "OLD GOLD"
        },
        "164": {
          "label": "LIGHT GOLD"
        },
        "165": {
          "label": "Traslucido"
        },
        "166": {
          "label": "azul Cielo"
        },
        "167": {
          "label": "Transparente"
        },
        "168": {
          "label": "MORADO"
        },
        "169": {
          "label": "AZUL MEDIA NOCHE"
        },
        "170": {
          "label": "Crema"
        },
        "171": {
          "label": "MW INDIGO"
        },
        "172": {
          "label": "SW INDIGO"
        },
        "173": {
          "label": "NEGRO MATE"
        },
        "174": {
          "label": "TURQUESA"
        },
        "175": {
          "label": "MIDNIGHT NAVY"
        },
        "176": {
          "label": "Naranja hi-vis"
        },
        "177": {
          "label": "Amarillo hi-vis"
        },
        "178": {
          "label": "Rosa Fosforescente"
        },
        "179": {
          "label": "Blaco/Rojo"
        },
        "180": {
          "label": "Bicolor"
        },
        "181": {
          "label": "Blanco/Rojo"
        },
        "182": {
          "label": "Dark Navy"
        },
        "183": {
          "label": "AZUL CELESTE"
        },
        "184": {
          "label": "GRIS OSCURO"
        },
        "185": {
          "label": "Oscuros"
        },
        "186": {
          "label": "Naranja/Amarillo"
        },
        "187": {
          "label": "GRIS MEDIO"
        },
        "188": {
          "label": "NO APLICA"
        },
        "189": {
          "label": "CLARO"
        },
        "190": {
          "label": "Traslucido Gris"
        },
        "191": {
          "label": "Kit"
        }
      }
    },
    "text_mkzp9428": {
      "id": "text_mkzp9428",
      "title": "Unidad",
      "type": "text"
    },
    "numeric_mkzpx7eb": {
      "id": "numeric_mkzpx7eb",
      "title": "Costo Distribuidor",
      "type": "numbers"
    },
    "text_mkzp59zf": {
      "id": "text_mkzp59zf",
      "title": "Moneda",
      "type": "text"
    },
    "numeric_mm0bnkch": {
      "id": "numeric_mm0bnkch",
      "title": "Gastos de envío e importación",
      "type": "numbers"
    },
    "numeric_mm0bgd2f": {
      "id": "numeric_mm0bgd2f",
      "title": "Descuento Distribuidor",
      "type": "numbers"
    },
    "text_mkzpbhb5": {
      "id": "text_mkzpbhb5",
      "title": "Descripcion licitacion",
      "type": "text"
    },
    "long_text_mm0xse7v": {
      "id": "long_text_mm0xse7v",
      "title": "Descripción cotización (largo)",
      "type": "long_text"
    },
    "text_mkzmgvc7": {
      "id": "text_mkzmgvc7",
      "title": "airtable id",
      "type": "text"
    },
    "pulse_updated_mkzttn57": {
      "id": "pulse_updated_mkzttn57",
      "title": "Última actualización",
      "type": "last_updated"
    },
    "dropdown_mm07pjsv": {
      "id": "dropdown_mm07pjsv",
      "title": "Grupo de producto",
      "type": "dropdown",
      "labels": {
        "1": {
          "label": "Producto"
        },
        "2": {
          "label": "Embellecimiento"
        },
        "3": {
          "label": "Nuevo Producto"
        }
      }
    },
    "text_mm0wvga2": {
      "id": "text_mm0wvga2",
      "title": "Nombre Producto",
      "type": "text"
    },
    "long_text_mm174q0j": {
      "id": "long_text_mm174q0j",
      "title": "Tallas JSON",
      "type": "long_text"
    },
    "long_text_mm1tcga0": {
      "id": "long_text_mm1tcga0",
      "title": "Historial precios",
      "type": "long_text"
    },
    "pulse_id_mm1w2z3h": {
      "id": "pulse_id_mm1w2z3h",
      "title": "ID de elemento",
      "type": "item_id"
    }
  },
  "instituciones": {
    "name": {
      "id": "name",
      "title": "Name",
      "type": "name"
    },
    "subtasks_mm0csftx": {
      "id": "subtasks_mm0csftx",
      "title": "Subelementos",
      "type": "subtasks"
    },
    "account_contact": {
      "id": "account_contact",
      "title": "Clientes",
      "type": "board_relation"
    },
    "text_mm1bvz12": {
      "id": "text_mm1bvz12",
      "title": "Municipio",
      "type": "text"
    },
    "dropdown_mm1bajsm": {
      "id": "dropdown_mm1bajsm",
      "title": "Tipo",
      "type": "dropdown",
      "labels": {
        "1": {
          "label": "Fiscalía"
        },
        "2": {
          "label": "Bomberos"
        },
        "3": {
          "label": "Municipio"
        },
        "4": {
          "label": "Secretaría de Seguridad Pública"
        },
        "5": {
          "label": "Protección Civil"
        },
        "6": {
          "label": "Seguridad y Fuerzas Armadas"
        },
        "7": {
          "label": "Protección Civil y Emergencias"
        },
        "8": {
          "label": "Otros"
        },
        "9": {
          "label": "Socio Comercial"
        },
        "10": {
          "label": "Procuraduria"
        },
        "11": {
          "label": "Opción nueva"
        }
      }
    },
    "dropdown_mm1brkww": {
      "id": "dropdown_mm1brkww",
      "title": "Grupo",
      "type": "dropdown",
      "labels": {
        "1": {
          "label": "Municipio"
        },
        "2": {
          "label": "Estados"
        },
        "3": {
          "label": "Federación"
        },
        "4": {
          "label": "Otros"
        }
      }
    },
    "numeric_mm1bv7zf": {
      "id": "numeric_mm1bv7zf",
      "title": "id_estado",
      "type": "numbers"
    },
    "numeric_mm1bgv1p": {
      "id": "numeric_mm1bgv1p",
      "title": "id_municipio",
      "type": "numbers"
    },
    "dropdown_mm1b46m9": {
      "id": "dropdown_mm1b46m9",
      "title": "Estado",
      "type": "dropdown",
      "labels": {
        "1": {
          "label": "Nuevo León"
        },
        "2": {
          "label": "Aguascalientes"
        },
        "3": {
          "label": "Guerrero"
        },
        "4": {
          "label": "Baja California Sur"
        },
        "5": {
          "label": "Coahuila de Zaragoza"
        },
        "6": {
          "label": "Campeche"
        },
        "7": {
          "label": "Tlaxcala"
        },
        "8": {
          "label": "Colima"
        },
        "9": {
          "label": "Veracruz de Ignacio de la Llave"
        },
        "10": {
          "label": "Chiapas"
        },
        "11": {
          "label": "Chihuahua"
        },
        "12": {
          "label": "Michoacán de Ocampo"
        },
        "13": {
          "label": "CDMX"
        },
        "14": {
          "label": "Hidalgo"
        },
        "15": {
          "label": "Tabasco"
        },
        "16": {
          "label": "Tamaulipas"
        },
        "17": {
          "label": "México"
        },
        "18": {
          "label": "Oaxaca"
        },
        "19": {
          "label": "Yucatán"
        },
        "20": {
          "label": "Sonora"
        },
        "21": {
          "label": "Baja California"
        },
        "22": {
          "label": "Querétaro"
        },
        "23": {
          "label": "Jalisco"
        },
        "24": {
          "label": "Zacatecas"
        },
        "25": {
          "label": "Durango"
        },
        "26": {
          "label": "Quintana Roo"
        },
        "27": {
          "label": "San Luis Potosí"
        },
        "28": {
          "label": "Guanajuato"
        },
        "29": {
          "label": "Sinaloa"
        },
        "30": {
          "label": "Morelos"
        },
        "31": {
          "label": "Puebla"
        },
        "32": {
          "label": "Nayarit"
        },
        "33": {
          "label": "Otros"
        },
        "34": {
          "label": "Ciudad de México"
        },
        "35": {
          "label": "Estado de México"
        },
        "36": {
          "label": "Hid"
        },
        "37": {
          "label": "Lima"
        },
        "38": {
          "label": "Pe-Lim"
        },
        "39": {
          "label": "Veracruz"
        },
        "40": {
          "label": "Distrito Federal"
        },
        "41": {
          "label": "Ec-P"
        },
        "42": {
          "label": "Méx"
        },
        "43": {
          "label": "Soltero(A)"
        },
        "44": {
          "label": "California"
        },
        "45": {
          "label": "Ab"
        },
        "46": {
          "label": "São Paulo"
        },
        "47": {
          "label": "Guatemala"
        },
        "48": {
          "label": "Gua"
        },
        "49": {
          "label": "Coyoacan"
        },
        "50": {
          "label": "Cortes"
        },
        "51": {
          "label": "Nuevo Leon"
        },
        "52": {
          "label": "Antioquia"
        },
        "53": {
          "label": "Venustiano Carranza"
        },
        "54": {
          "label": "Chp"
        },
        "55": {
          "label": "Chilpancingo"
        },
        "56": {
          "label": "Michoacán"
        },
        "57": {
          "label": "Lille"
        },
        "58": {
          "label": "Michoacan"
        }
      }
    },
    "text_mm0canq": {
      "id": "text_mm0canq",
      "title": "RFC",
      "type": "text"
    },
    "text_mm0cdqv2": {
      "id": "text_mm0cdqv2",
      "title": "Domicilio Fiscal",
      "type": "text"
    },
    "text_mm0c7qw1": {
      "id": "text_mm0c7qw1",
      "title": "Régimen Fiscal",
      "type": "text"
    },
    "date_mm0cv76t": {
      "id": "date_mm0cv76t",
      "title": "Fin de Administración",
      "type": "date"
    },
    "file_mm0ccv71": {
      "id": "file_mm0ccv71",
      "title": "Documentos",
      "type": "file"
    },
    "multiple_person_mm0c3xbk": {
      "id": "multiple_person_mm0c3xbk",
      "title": "Vendedor",
      "type": "people"
    },
    "board_relation_mm0ha84m": {
      "id": "board_relation_mm0ha84m",
      "title": "Proyectos",
      "type": "board_relation"
    },
    "text_mm1bped1": {
      "id": "text_mm1bped1",
      "title": "id_inegi",
      "type": "text"
    }
  },
  "contactos": {
    "name": {
      "id": "name",
      "title": "Name",
      "type": "name"
    },
    "subtasks_mkvpdgxr": {
      "id": "subtasks_mkvpdgxr",
      "title": "Subitems",
      "type": "subtasks"
    },
    "multiple_person_mm03vqwx": {
      "id": "multiple_person_mm03vqwx",
      "title": "Vendedor",
      "type": "people"
    },
    "custom_mkrm9y8c": {
      "id": "custom_mkrm9y8c",
      "title": "Actividades",
      "type": "unsupported"
    },
    "contact_account": {
      "id": "contact_account",
      "title": "Institución",
      "type": "board_relation"
    },
    "contact_email": {
      "id": "contact_email",
      "title": "Email",
      "type": "email"
    },
    "contact_phone": {
      "id": "contact_phone",
      "title": "Teléfono",
      "type": "phone"
    },
    "text_mm0dz8yj": {
      "id": "text_mm0dz8yj",
      "title": "Cargo",
      "type": "text"
    },
    "long_text4": {
      "id": "long_text4",
      "title": "Comentarios",
      "type": "long_text"
    },
    "pulse_log_mm1t6x5s": {
      "id": "pulse_log_mm1t6x5s",
      "title": "Registro de creación",
      "type": "creation_log"
    },
    "text_mm454qq1": {
      "id": "text_mm454qq1",
      "title": "Prioridad",
      "type": "text"
    },
    "text_mm45xn3": {
      "id": "text_mm45xn3",
      "title": "Calificación",
      "type": "text"
    },
    "text_mm45tqrm": {
      "id": "text_mm45tqrm",
      "title": "Ciudad",
      "type": "text"
    },
    "text_mm456fbp": {
      "id": "text_mm456fbp",
      "title": "Estado",
      "type": "text"
    },
    "text_mm562a0m": {
      "id": "text_mm562a0m",
      "title": "Cargo",
      "type": "text"
    }
  }
};
