#!/usr/bin/env node
// scripts/introspect-boards.mjs — pulls column titles/types/status-labels from
// Monday and (re)generates shared/column-meta.gen.ts.
// Usage: node --env-file=.env scripts/introspect-boards.mjs
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { BOARDS } from '../shared/boards.ts';
import { gql } from '../worker/lib/monday.ts';

const MONDAY_API_KEY = process.env.MONDAY_API_KEY;
if (!MONDAY_API_KEY) {
  console.error('MONDAY_API_KEY missing — run with: node --env-file=.env scripts/introspect-boards.mjs');
  process.exit(1);
}
const env = { MONDAY_API_KEY };

// Status columns: settings_str.labels = {"idx":"Label"}, labels_colors = {"idx":{color}}.
// Dropdown columns: settings_str.labels = [{id,name}], no reliable colors.
function parseLabels(settingsStr) {
  if (!settingsStr) return undefined;
  let s;
  try { s = JSON.parse(settingsStr); } catch { return undefined; }
  const out = {};
  if (Array.isArray(s.labels)) {
    for (const l of s.labels) {
      if (l?.id === undefined || l.id === null) continue;
      const color = s.labels_colors?.[String(l.id)]?.color;
      out[String(l.id)] = color ? { label: l.name, color } : { label: l.name };
    }
  } else if (s.labels && typeof s.labels === 'object') {
    for (const [idx, label] of Object.entries(s.labels)) {
      const color = s.labels_colors?.[idx]?.color;
      out[idx] = color ? { label, color } : { label };
    }
  } else {
    return undefined;
  }
  return Object.keys(out).length ? out : undefined;
}

async function main() {
  const ids = Object.values(BOARDS).map(def => String(def.id));
  const data = await gql(
    env,
    `query($ids:[ID!]){ boards(ids:$ids){ id columns{ id title type settings_str } } }`,
    { ids },
  );

  const bySlug = {};
  for (const def of Object.values(BOARDS)) {
    const board = data.boards.find(b => Number(b.id) === def.id);
    if (!board) { console.warn(`WARNING: board ${def.slug} (${def.id}) not found in response`); continue; }
    const cols = {};
    for (const c of board.columns) {
      const labels = parseLabels(c.settings_str);
      cols[c.id] = { id: c.id, title: c.title, type: c.type, ...(labels ? { labels } : {}) };
    }
    bySlug[def.slug] = cols;
    console.log(`${def.slug}: ${Object.keys(cols).length} columns`);
  }

  const out = `// GENERATED by scripts/introspect-boards.mjs — do not edit.
// Column titles/types/status-dropdown-labels straight from Monday (API 2024-10),
// keyed by board slug then column id. Re-run the script to refresh.
import type { BoardSlug } from './boards';
import type { ColMeta } from './dto';

export const COLUMN_META: Record<BoardSlug, Record<string, ColMeta>> = ${JSON.stringify(bySlug, null, 2)};
`;

  const outPath = fileURLToPath(new URL('../shared/column-meta.gen.ts', import.meta.url));
  writeFileSync(outPath, out);
  console.log(`\nWrote ${outPath}`);
}

main().catch(e => { console.error(e); process.exit(1); });
